config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :photos, except: [:new] do
    collection do
      get 'manage'
    end
  end

  root "photos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :photos

  def sgid
    self.to_sgid.to_s
  end
end

app/models/group_photo.rb
class GroupPhoto < ApplicationRecord
  self.table_name = "groups_photos"

  belongs_to :group
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  store :metadata, accessors: [
    :camera_name, :lens, :iso, :shutter_speed, :aperture, :date_taken
  ], coder: JSON

  has_and_belongs_to_many :groups

  has_one_attached :asset do |asset|
    asset.variant :large, resize_to_limit: [1000, 1000], format: :jpeg, saver: { quality: 90 }
    asset.variant :thumb, resize_to_fill: [400, 400, crop: :centre], format: :png
  end

  #noinspection RubyResolve
  def after_create
    exif = asset.open { |file| Exif::Data.new(file) }

    self.metadata[:camera_name] = "#{exif.make.capitalize} #{exif.model}"
    self.metadata[:lens] = exif[:exif][:lens_model]
    self.metadata[:iso] = exif[:exif][:iso_speed_ratings]
    self.metadata[:shutter_speed] = exif[:exif][:exposure_time]
    self.metadata[:aperture] = exif[:exif][:fnumber].to_r.to_f
    self.metadata[:date_taken] = exif[:exif][:date_time_original]

    self.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.json { render json: @group.to_json(methods: :sgid), status: :created }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[ show edit destroy ]

  # GET /photos or /photos.json
  def index
    @photos = Photo.all
    @groups = Group.all
  end

  def manage
    @groups = Group.all
    @photos = Photo.all.order(created_at: :desc)
    @photo = Photo.new

    if params[:filter_group] == 'ungrouped'
      @filtered_group = Group.new(name: 'Ungrouped')
      @photos = Photo.where.missing(:groups).order(created_at: :desc)
    elsif params[:filter_group] and params[:filter_group].match? /\A\d+\z/
      @filtered_group = Group.find(params[:filter_group])
      @photos = @filtered_group.photos.order(created_at: :desc).uniq
    end

    @photos = @photos
  end

  # GET /photos/1 or /photos/1.json
  def show
  end

  # GET /photos/1/edit
  def edit
  end

  def create
    @photos = []

    Photo.transaction do
      # compact_blank! because for some godawful reason
      # the form gets generated with a stray blank field.
      # why
      photo_params[:assets].compact_blank!.each do |asset|
        new_photo = Photo.new(asset: asset)
        @photos << new_photo
        new_photo.save
      end
    end

    respond_to do |format|
      format.turbo_stream
    end
  end

  def update
    selected_photos = GlobalID::Locator.locate_many_signed params[:selected_photos]
    selected_groups = GlobalID::Locator.locate_many_signed params[:selected_groups]

    new_relations = selected_photos.pluck(:id)
                                   .product(selected_groups.pluck(:id))
                                   .map { |p, g| { photo_id: p, group_id: g } }

    GroupPhoto.insert_all new_relations

    respond_to do |format|
      format.json { render json: {
        photos_updated: selected_photos.count,
        groups_updated: selected_groups.count
      }, status: :ok }
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(assets: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(name, path)
    content_tag :li, link_to(name,
                             path,
                             class: "nav-link #{'active' if current_page? path} px-2",
                             aria_current: ('page' if current_page? path)),
                class: 'mx-1'
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
  def filter_option_for(group)
    if group == 'ungrouped'
      text = safe_join([ 'Ungrouped', raw('<i class="bi bi-asterisk float-end"></i>') ])
    else
      text = safe_join([
                         group.name,
                         raw("<i class=\"bi bi-folder#{'-fill' if is_current_filter?(group)} float-end\"></i>")
                       ])
    end
      link_to text,
              manage_photos_path(filter_group: (group.is_a?(Group) ? group.id : 'ungrouped')),
              class: "nav-link#{' active' if is_current_filter?(group)}",
              aria_current: (true if is_current_filter?(group))
    end

  private

  def is_current_filter?(group)
    if group.is_a? Group
      params[:filter_group].to_i == group.id
    else
      params[:filter_group] == 'ungrouped'
    end
  end
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
  <p>
    <strong>Name:</strong>
    <%= group.name %>
  </p>

</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Albums</h1>

<div class="row g-2">
  <% @groups.each do |group| %>
    <div class="col-6 col-sm-4 col-md-2">
      <div class="card border-0 bg-dark">
        <%= link_to group, class: 'photo' do %>
          <%= image_tag group.photos.first.asset.variant(:thumb), class: 'card-img' %>

          <div class="card-img-overlay bg-dark bg-gradient bg-opacity-25 text-white d-flex flex-column">
            <h5 class="card-title mt-auto mb-0"><%= group.name %></h5>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FiveMin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "navbar", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag params[:controller] %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="vh-100">
    <%= render 'partials/navbar' %>

    <div class="container mt-3 h-100">
      <%= yield %>
    </div>

    <div class="toast-container position-fixed bottom-0 end-0 p-3" id="toastContainer">
      <template id="toastTemplate">
        <div class="toast align-items-center border-0"
             role="alert" aria-live="assertive" aria-atomic="true">
          <div class="d-flex">
            <div class="toast-body"></div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto"
                    data-bs-dismiss="toast" aria-label="Close"></button>
          </div>
        </div>
      </template>
    </div>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container">
    <%= link_to 'FiveMin', root_path, class: 'navbar-brand mb-0 h1' %>
    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse mt-2 mt-lg-0" id="navbarNav">
      <ul class="navbar-nav">
        <%= nav_link 'Albums', groups_path %>
      </ul>
      <hr class="d-lg-none">
      <ul class="navbar-nav ms-auto">
        <%= nav_link 'Photo Manager', manage_photos_path %>
      </ul>
    </div>
  </div>
</nav>

app/views/photos/_browser_pane.html.erb
<div class="card text-bg-light h-75">
  <div class="card-header">
    Filter
  </div>
  <div class="card-body p-1">
    <nav class="nav nav-pills flex-column">
      <%= filter_option_for 'ungrouped' %>
      <% @groups.each do |group| %>
        <%= filter_option_for group %>
      <% end %>
    </nav>
  </div>
</div>

app/views/photos/_form.html.erb
<div class="modal fade"
     id="uploadModal"
     tabindex="-1"
     aria-labelledby="uploadModalLabel"
     aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="uploadModalLabel">Upload Photos</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_with(model: @photo, data: {
        controller: 'photo-manager--upload',
        photo_manager__upload_target: 'uploadForm',
        action: 'turbo:submit-end->photo-manager--upload#reset'
      }) do |form| %>
        <div class="modal-body">
          <%= form.label :assets, 'Attach at least one image...', class: 'form-label' %>
          <%= form.file_field :assets, multiple: true, direct_upload: true, class: 'form-control' %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= form.submit 'Upload', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/photos/_keyboard_reference.html.erb
<div data-controller="photo-manager--keyboard-modal">
  <button type="button"
          class="btn btn-sm btn-outline-secondary mt-3"
          data-bs-toggle="modal"
          data-bs-target="#keyboardReference">
    <i class="bi bi-command"></i>
  </button>

  <div class="modal fade"
       id="keyboardReference"
       tabindex="-1"
       aria-labelledby="keyboardReferenceLabel"
       aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="keyboardReferenceLabel">Keyboard Shortcuts</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <table class="table">
            <tbody>
            <thead>
            <tr>
              <th scope="col">Shortcut</th>
              <th scope="col">Behaviour</th>
            </tr>
            </thead>
            <tbody>
            <tr>
              <th scope="row">/</th>
              <td>Show this reference</td>
            </tr>
            <tr>
              <th scope="row">N</th>
              <td>Show the photo upload menu</td>
            </tr>
            <tr>
              <th scope="row">S</th>
              <td>Toggle selection mode</td>
            </tr>
            <tr>
              <th scope="row"><i class="bi bi-command"></i> A</th>
              <td>Select everything</td>
            </tr>
            <tr>
              <th scope="row"><i class="bi bi-command"></i> D</th>
              <td>Deselect everything</td>
            </tr>
            <tr>
              <th scope="row"><i class="bi bi-shift"></i><i class="bi bi-mouse2"></i></th>
              <td>After selecting an image, hold shift and select another to select the range between them</td>
            </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/photos/_photo.html.erb
<div class="col-6 col-sm-4 col-md-2">
  <%= link_to photo, class: 'photo', data: { action: 'gallery#toggleSelect', sgid: photo.to_sgid_param } do %>
    <%= image_tag photo.asset.variant(:thumb), class: 'rounded' %>
  <% end %>
</div>

app/views/photos/_uploader.html.erb
<div class="d-grid mb-3" data-controller="photo-manager--upload">
  <button type="button"
          class="btn btn-outline-primary"
          data-bs-toggle="modal"
          data-bs-target="#uploadModal">
    <i class="bi bi-upload me-2"></i>
    Upload Photos
  </button>
</div>

<%= render 'form', photo: @photo %>

app/views/photos/create.turbo_stream.erb
<% @photos.each do |photo| %>
  <%= turbo_stream.prepend 'photos' do %>
    <%= render photo %>
  <% end %>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Show this photo", @photo %> |
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/index.html.erb
<p style="color: green"><%= notice %></p>

<div data-controller="gallery">
  <div class="hstack">
    <h2 class="me-auto mb-0">All Photos</h2>

    <div class="hstack ms-auto">
      <div class="btn-group" role="group" aria-label="Grouping actions">
        <button class="btn btn-outline-primary"
                data-bs-toggle="button"
                data-action="gallery#toggleSelecting"
                data-gallery-target="toggler">
          Select
        </button>
        <button class="btn btn-outline-secondary"
                data-bs-toggle="button"
                data-action="gallery#toggleSelecting"
                data-gallery-target="finalizeButton"
                disabled>
          Group...
        </button>
      </div>
      <%= select_tag 'group-selector',
                     options_from_collection_for_select(@groups, 'to_sgid', 'name'),
                     class: 'form-select ms-2',
                     placeholder: 'Select groups...',
                     multiple: true,
                     autocomplete: 'off',
                     data: { gallery_target: 'groupSelector' } %>
    </div>
  </div>

  <div class="input-group mb-2">
    <button class="btn btn-secondary"
            data-action="gallery#updateGroups">
      Add to group(s)
    </button>
  </div>

  <div class="row">
    <div class="col-lg-2">
      <div class="card text-bg-light h-100">
        <div class="card-header">
          Filters
        </div>
        <div class="card-body">
          <% @groups.each do |group| %>
            <%= link_to  %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="row g-2 gallery" data-gallery-target="gallery">
        <% @photos.each do |photo| %>
          <div class="col-6 col-sm-4 col-md-2">
            <%= link_to photo, class: 'photo', data: { action: 'gallery#toggleSelect', sgid: photo.to_sgid_param } do %>
              <%= image_tag photo.asset.variant(:thumb), class: 'rounded' %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/photos/manage.html.erb
<div data-controller="gallery">
  <%# select_tag 'group-selector',
                 options_from_collection_for_select(@groups, 'to_sgid', 'name'),
                 class: 'form-select ms-2',
                 placeholder: 'Select groups...',
                 multiple: true,
                 autocomplete: 'off',
                 data: { gallery_target: 'groupSelector' } %>
<!--  <button class="btn btn-secondary"-->
<!--          data-action="gallery#updateGroups">-->
<!--    Add to group(s)-->
<!--  </button>-->

  <div class="row">
    <div class="col-lg-2 vh-100 mb-5">
      <%= render 'uploader' %>
      <%= render 'browser_pane' %>
      <%= render 'keyboard_reference' %>
    </div>

    <div class="col">
      <div class="hstack mb-3">
        <nav aria-label="breadcrumb" class="ms-1">
          <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item<%= ' active' unless @filtered_group %>">
              <%= @filtered_group ? link_to('All Photos', manage_photos_path) : 'All Photos' %>
            </li>
            <% if @filtered_group %>
              <li class="breadcrumb-item active"><%= @filtered_group.name %></li>
            <% end %>
          </ol>
        </nav>

        <div class="btn-group ms-auto" role="group" aria-label="Grouping actions">
          <button class="btn btn-outline-primary"
                  data-bs-toggle="button"
                  data-action="gallery#toggleSelecting"
                  data-gallery-target="toggler">
            Select
          </button>
          <button class="btn btn-outline-secondary"
                  data-bs-toggle="button"
                  data-action="gallery#openGroupModal"
                  data-gallery-target="groupButton"
                  disabled>
            Group...
          </button>
        </div>
      </div>

      <div id="photos" class="row g-2 gallery" data-gallery-target="gallery">
        <%= render @photos %>
      </div>
    </div>

  </div>
</div>

app/views/photos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @photo %>

<div>
  <%= link_to "Edit this photo", edit_photo_path(@photo) %> |
  <%= link_to "Back to photos", photos_path %>

  <%= button_to "Destroy this photo", @photo, method: :delete %>
</div>